'use client';

import React, { useState } from 'react';
import Image from 'next/image';

interface OptimizedImageV2Props {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  className?: string;
  priority?: boolean;
  fill?: boolean;
  aspectRatio?: string;
  sizes?: string;
  quality?: number;
  loading?: 'lazy' | 'eager';
  placeholder?: 'blur' | 'empty';
  blurDataURL?: string;
  // Specific optimization controls
  useBlur?: boolean;
}

/**
 * Enhanced OptimizedImage component for static export with build-time optimized images
 * 
 * This component expects images have been processed by the optimize-images.js script
 * which generates responsive WebP and AVIF variants
 */
export function OptimizedImageV2({
  src,
  alt,
  width,
  height,
  className = '',
  priority = false,
  fill = false,
  aspectRatio,
  sizes,
  quality = 75,
  loading = 'lazy',
  placeholder = 'empty',
  blurDataURL,
  useBlur = true,
  ...props
}: OptimizedImageV2Props) {
  const [imageError, setImageError] = useState(false);

  if (imageError) {
    return (
      <div 
        className={`flex items-center justify-center bg-neutral-100 text-neutral-400 ${className}`}
        style={aspectRatio ? { aspectRatio } : {}}
      >
        <svg
          className="w-8 h-8"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
          />
        </svg>
      </div>
    );
  }

  // Extract file information
  const getBaseFilename = (url: string): string => {
    const filename = url.split('/').pop() || '';
    return filename.substring(0, filename.lastIndexOf('.'));
  };

  const getBasePath = (url: string): string => {
    const parts = url.split('/');
    parts.pop();
    return parts.join('/');
  };

  const baseFilename = getBaseFilename(src);
  const basePath = getBasePath(src);

  // For LCP images, use priority loading
  if (priority && loading === 'lazy') {
    loading = 'eager';
  }

  // Generate blur data URL for placeholder if needed
  let finalBlurDataURL = blurDataURL;
  if (useBlur && placeholder === 'blur' && !finalBlurDataURL) {
    // Try to use the tiny thumbnail generated by our build script
    finalBlurDataURL = `${basePath}/${baseFilename}-tiny.jpg`;
  }

  // Wrapper div for aspect ratio or fill
  const imageContainer = (
    <div className={fill ? 'relative' : ''} style={fill ? {} : aspectRatio ? { aspectRatio } : {}}>
      <picture>
        {/* AVIF source - most efficient modern format */}
        <source
          type="image/avif"
          srcSet={`
            ${basePath}/${baseFilename}-640.avif 640w,
            ${basePath}/${baseFilename}-1024.avif 1024w,
            ${basePath}/${baseFilename}-1600.avif 1600w,
            ${basePath}/${baseFilename}-1920.avif 1920w
          `}
          sizes={sizes}
        />
        {/* WebP source - fallback for browsers without AVIF */}
        <source
          type="image/webp"
          srcSet={`
            ${basePath}/${baseFilename}-640.webp 640w,
            ${basePath}/${baseFilename}-1024.webp 1024w,
            ${basePath}/${baseFilename}-1600.webp 1600w,
            ${basePath}/${baseFilename}-1920.webp 1920w
          `}
          sizes={sizes}
        />
        {/* Fallback to original format */}
        <Image
          src={src}
          alt={alt}
          width={width}
          height={height}
          fill={fill}
          sizes={sizes}
          quality={quality}
          loading={loading}
          priority={priority}
          placeholder={placeholder}
          blurDataURL={finalBlurDataURL}
          className={`${className} ${fill ? 'object-cover' : ''}`}
          onError={() => setImageError(true)}
          unoptimized // Important for static export
          {...props}
        />
      </picture>
    </div>
  );

  return imageContainer;
}

// Helper function to preload critical images
export function preloadImage(src: string, priority: boolean = true) {
  const baseFilename = src.split('/').pop()?.split('.')[0] || '';
  const basePath = src.split('/').slice(0, -1).join('/');
  
  // Preload AVIF (most efficient) first
  if (priority && typeof window !== 'undefined') {
    const avifLink = document.createElement('link');
    avifLink.rel = 'preload';
    avifLink.as = 'image';
    avifLink.type = 'image/avif';
    avifLink.fetchPriority = 'high';
    document.head.appendChild(avifLink);
    
    // Fallback to WebP for older browsers
    const webpLink = document.createElement('link');
    webpLink.rel = 'preload';
    webpLink.as = 'image';
    webpLink.type = 'image/webp';
    webpLink.fetchPriority = 'high';
    document.head.appendChild(webpLink);
  }
}

// Special component for hero images with advanced optimization
export function HeroImage({
  src,
  alt,
  className = '',
  ...props
}: Omit<OptimizedImageV2Props, 'priority'>) {
  return (
    <OptimizedImageV2
      src={src}
      alt={alt}
      priority={true} // Always priority for hero images
      loading="eager"
      placeholder="blur"
      sizes="100vw"
      className={`transition-all duration-500 ${className}`}
      {...props}
    />
  );
}

// Special component for logo images with specific optimizations
export function LogoImage({
  src,
  alt,
  className = '',
  ...props
}: OptimizedImageV2Props) {
  return (
    <OptimizedImageV2
      src={src}
      alt={alt}
      priority={false}
      placeholder="empty"
      sizes="(max-width: 768px) 48px, 64px"
      className={`transition-transform duration-300 hover:scale-110 ${className}`}
      {...props}
    />
  );
}